export const textboxIcon: string
export const green: string
export const orange: string
export const red: string
export const dropdown: string
export const content: string
export const noResults: string
export const iframeInfo: string
export const inputWrapper: string
export const copyIcon: string
export const success: string
export const item: string
export const primaryText: string
export const selected: string
export const footer: string
export const logo: string
export const saveWrap: string
export const saveIframe: string
export const icon: string
export const box: string
export const boxContent: string
export const iconContainter: string
export const listContainter: string
